### PR TITLE
2.0.0-beta.0 tested

### PR DESCRIPTION
**Pull request by DSorlov**
Suggested update to support modern config and to add to HACS.

Status: Tested and working on multiple installs.
Missing brands repos otherwise ready for HACS inclusion

### Added
- Added binary sensors for news and alerts
- Added a device for future enhancements
- Integration configuration using GUI (config_flow)
- System status information (system_health)
- info.md and hacs.json to prepare to add to HACS
- Dependency on httpx for better control of http operations
- Communication library (kriscom) to follow design guidance
- English translation for GUI

### Changed
- Changed default sensor property to number of messages
- Sensor icon changes due to severity and status of the sensor
- Version set to 2.0.0-beta.0 as it is breaking changes
- Updated package.yaml legacy package information file

### CODE REVIEW

**Comment by isabellaalstrom** [comment]
Tack 😍

**Comment by isabellaalstrom** [comment]
I would like to specify that you can still use other coordinates than home and also county or country. For the read me. Trying it out now!

**Comment by DSorlov** [comment]
> I would like to specify that you can still use other coordinates than home and also county or country. For the read me. Trying it out now!

Oh! But you can, I think I got all options except name as options. Once you installed it you can configure it to use custom coordinates.

right now however I think you could only have one integration but it would be pretty simple to fix the worker to have multiple instances.

**Comment by DSorlov** [comment]
Readme would need to be further updated also, and if a brand repo is created and it is added to HACS that would also change the actuall install steps also.

**Comment by filikun** [comment]
Not sure if there is the right place for feedback on but here it goes! 

1, First and foremost the config in the GUI seems not savable, it just bounces back to the default.
2, Make clear how the config input should look like for example is `Country` SE, Sweden, SV, Sverige?/is county Skåne läm, Skåne, Skane etc. (I think you had this in previous readme?)

Just to make it clear, here it how it looks when trying configure it in the GUI in order.
image
image
image

**Pull request merged**
